In [1]:
import numpy as np
import scipy as sc
import pandas as pd
from fractions import Fraction
from math import sqrt
import xml.dom.minidom

In [2]:
def getPages():
    doc=xml.dom.minidom.parse(r'WebPageSmall.xml')
    pagesList=[]
    totalLinks=[]
    pages=doc.getElementsByTagName('page')
    for page in pages:
        listeLinks=[]
        pagesList.append(page.getAttribute("PageName"))
        Links=page.getElementsByTagName("link")
        for l in range(len(Links)):
            listeLinks.append(Links[l].firstChild.nodeValue)  
        totalLinks.append(listeLinks)
    return pagesList,totalLinks

In [3]:
def transportation():
    pages, Links=getPages()
    print("===============================")
    for i in range(len(pages)):
        print(pages[i]," has links to: ",Links[i])
    print("==================Transportation==============")
    matrice=np.zeros((len(pages),len(pages)))
    for i in range(len(pages)):
        for j in range(len(pages)):
            if pages[j] in Links[i]:
                matrice[i][j]=0.85*1/len(Links[i])
    print(matrice)
    print("===============================")
    return matrice

In [4]:
def isdangling():
    pages, Links=getPages()
    dangling=[]
    index=[]
    for i in range(len(pages)):
        if not Links[i] :
            dangling.append(pages[i])
            index.append(i)
    return dangling,index

In [5]:
dangling,indexdang=isdangling()
print("==========Dangling Nodes")
for i in range(len(dangling)):
    print("dangling node is : ",dangling[i],"his index is :",indexdang[i])
#print(dangling)
#print(indexdang)

==========Dangling Nodes
dangling node is :  D his index is : 3


In [6]:
Pages=["A","B","C","D"]
#this ligne about the file webPageCours that contains a another example xml describing another graph of webpages 
#Pages=["A","B","C","D","E","F","G","H","I","L","M"]
Mat=transportation()

A  has links to:  ['B', 'C']
B  has links to:  ['D']
C  has links to:  ['A', 'B', 'D']
D  has links to:  []
==================Transportation==============
[[0.         0.425      0.425      0.        ]
 [0.         0.         0.         0.85      ]
 [0.28333333 0.28333333 0.         0.28333333]
 [0.         0.         0.         0.        ]]


In [7]:
nbr_pages=len(Pages)
Ex = np.zeros((nbr_pages,nbr_pages))
Ex1 = np.zeros((nbr_pages,nbr_pages))
Ex[:] = 0.15/nbr_pages
Ex1[:] = 1/nbr_pages

for i in indexdang:
    Ex[i,:]=Ex1[i,:]
print("==========Teleportation===============")
print(Ex)

==========Teleportation===============
[[0.0375 0.0375 0.0375 0.0375]
 [0.0375 0.0375 0.0375 0.0375]
 [0.0375 0.0375 0.0375 0.0375]
 [0.25   0.25   0.25   0.25  ]]


In [8]:
print("============ Random Surfing Probability==========")
print(Ex+Mat)

============ Random Surfing Probability==========
[[0.0375     0.4625     0.4625     0.0375    ]
 [0.0375     0.0375     0.0375     0.8875    ]
 [0.32083333 0.32083333 0.0375     0.32083333]
 [0.25       0.25       0.25       0.25      ]]
